server :
  port : 8081

info:
  app:
    encodig: UTF-8
    java:
      source: 1.8
      target: 1.8
  name:
    of:
      app: Invoice Server Test
management:
  endpoint:
    health:
      show-details: always
spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/invoice
    username: root
  main:
    banner-mode: 'off'
